# Generated by Django 4.0.3 on 2022-04-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
