# Generated by Django 4.0.3 on 2022-05-19 17:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Extra info persoon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics', verbose_name='Profiel foto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefoonnummer in formaat +31600000000.', max_length=128, null=True, region=None, unique=True, verbose_name='Telefoonnummer'),
        ),
    ]
