# Generated by Django 4.0.3 on 2022-05-22 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_historicalcustomuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecialisms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialism', models.CharField(max_length=100, verbose_name='Specialisme')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschrijving')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='centralist',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verkeersregelaar',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='centralist',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='verkeersregelaar',
        ),
        migrations.CreateModel(
            name='HistoricalUserSpecialisms',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('specialism', models.CharField(max_length=100, verbose_name='Specialisme')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschrijving')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user specialisms',
                'verbose_name_plural': 'historical user specialismss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialism',
            field=models.ManyToManyField(blank=True, null=True, to='users.userspecialisms'),
        ),
    ]
