# Generated by Django 4.0.3 on 2022-05-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userspecialisms_remove_customuser_centralist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalUserSpecialisms',
            new_name='HistoricalUserSpecialism',
        ),
        migrations.RenameModel(
            old_name='UserSpecialisms',
            new_name='UserSpecialism',
        ),
        migrations.AlterModelOptions(
            name='historicaluserspecialism',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user specialism', 'verbose_name_plural': 'historical user specialisms'},
        ),
    ]
