# Generated by Django 4.0.3 on 2022-05-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_specialism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialism',
            field=models.ManyToManyField(blank=True, default=2, help_text='Houd control/command ingedrukt om meerdere te selecteren.', to='users.userspecialism', verbose_name='Specialisme(n)'),
        ),
        migrations.AlterField(
            model_name='historicaluserspecialism',
            name='colorcode',
            field=models.CharField(default='bg-secondary', help_text='See Bootstrap badges: https://getbootstrap.com/docs/5.0/components/badge/ (enter class after badge)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserspecialism',
            name='icon',
            field=models.CharField(blank=True, help_text='See fa-icons: https://fontawesome.com/v5/icons (enter class)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userspecialism',
            name='colorcode',
            field=models.CharField(default='bg-secondary', help_text='See Bootstrap badges: https://getbootstrap.com/docs/5.0/components/badge/ (enter class after badge)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userspecialism',
            name='icon',
            field=models.CharField(blank=True, help_text='See fa-icons: https://fontawesome.com/v5/icons (enter class)', max_length=100, null=True),
        ),
    ]
