# Generated by Django 4.0.3 on 2022-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_specialism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialism',
            field=models.ManyToManyField(blank=True, default=1, help_text='Houd control/command ingedrukt om meerdere te selecteren.', to='users.userspecialism', verbose_name='Specialisme(n)'),
        ),
    ]
