# Generated by Django 4.0.3 on 2022-04-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='')),
                ('added_by', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
