# Generated by Django 4.0.3 on 2022-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_historicallog_deleted_log_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='log_files', verbose_name='Bestanden'),
        ),
        migrations.AlterField(
            model_name='log',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='log_files', verbose_name=''),
        ),
    ]
