# Generated by Django 4.0.3 on 2022-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='maplocation_x',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='maplocation_y',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
