# Generated by Django 4.0.3 on 2022-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_alter_post_maplocation_x_alter_post_maplocation_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_abbr',
            field=models.SlugField(blank=True, max_length=5, null=True),
        ),
    ]
