# Generated by Django 4.0.3 on 2022-04-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_rename_remove_planning_removed_planning_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central.shift'),
        ),
    ]
