# Generated by Django 4.0.3 on 2022-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_alter_planning_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='customdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
