# Generated by Django 4.0.3 on 2022-03-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_alter_post_post_abbr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_abbr',
            new_name='postslug',
        ),
    ]
