# Generated by Django 4.0.3 on 2022-03-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_rename_post_abbr_post_postslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
