# Generated by Django 4.0.3 on 2022-04-18 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0004_planning_customdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.TimeField()),
                ('timeend', models.TimeField()),
                ('timename', models.IntegerField(help_text='Number of the shift')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Day',
            new_name='ShiftDay',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='customdate',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='customend',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='customstart',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='shift',
        ),
        migrations.AddField(
            model_name='planning',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AddField(
            model_name='planning',
            name='endtime',
            field=models.TimeField(blank=True, null=True, verbose_name='Eindtijd'),
        ),
        migrations.AddField(
            model_name='planning',
            name='starttime',
            field=models.TimeField(blank=True, null=True, verbose_name='Starttijd'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Opmerking(en)'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Bevestigd'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Verwijderd'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Persoon'),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
