# Generated by Django 4.0.3 on 2022-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_historicalshifttime_historicalpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanning',
            name='copy_of',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='copy_of',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
