# Generated by Django 4.0.3 on 2022-05-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0008_historicalplanning_copy_of_planning_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanning',
            name='signed_of',
            field=models.BooleanField(default=False, verbose_name='Afgemeld'),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='signed_of_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planning',
            name='signed_of',
            field=models.BooleanField(default=False, verbose_name='Afgemeld'),
        ),
        migrations.AddField(
            model_name='planning',
            name='signed_of_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_of_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
