# Generated by Django 4.0.3 on 2022-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_historicalplanning_signed_of_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplanning',
            old_name='signed_of',
            new_name='signed_off',
        ),
        migrations.RenameField(
            model_name='historicalplanning',
            old_name='signed_of_by',
            new_name='signed_off_by',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='signed_of',
            new_name='signed_off',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='signed_of_by',
            new_name='signed_off_by',
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='signed_off_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Afmeldtijd'),
        ),
        migrations.AddField(
            model_name='planning',
            name='signed_off_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Afmeldtijd'),
        ),
    ]
