# Generated by Django 4.0.3 on 2022-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0010_rename_signed_of_historicalplanning_signed_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanning',
            name='external',
            field=models.BooleanField(default=False, help_text='Kan op meerdere posten staan en wordt automatisch bevestigd en afgemeld van post.', verbose_name='Externe verkeersregelaar'),
        ),
        migrations.AddField(
            model_name='planning',
            name='external',
            field=models.BooleanField(default=False, help_text='Kan op meerdere posten staan en wordt automatisch bevestigd en afgemeld van post.', verbose_name='Externe verkeersregelaar'),
        ),
    ]
