# Generated by Django 4.0.3 on 2022-06-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0012_historicalplanning_bike_historicalplanning_porto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplanning',
            name='bike',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='bike',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
