# Generated by Django 4.0.3 on 2023-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0014_sector_alter_historicalplanning_bike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
