# Generated by Django 4.0.3 on 2023-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0015_alter_historicalsector_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplanning',
            name='porto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Portofoon'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='porto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Portofoon'),
        ),
    ]
