# Generated by Django 4.0.3 on 2023-05-21 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0016_alter_historicalplanning_porto_alter_planning_porto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, unique=True, verbose_name='Nummmer')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam')),
                ('active', models.BooleanField(default=False, verbose_name='Actief')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notities')),
                ('primary_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hoofdgebruiker (hele weekend)')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalShiftDay',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('dayname', models.SlugField(max_length=15, verbose_name='Dag')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Extra info dag')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift day',
                'verbose_name_plural': 'historical shift days',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPorto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, db_index=True, verbose_name='Nummmer')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam')),
                ('active', models.BooleanField(default=False, verbose_name='Actief')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notities')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Hoofdgebruiker (hele weekend)')),
            ],
            options={
                'verbose_name': 'historical porto',
                'verbose_name_plural': 'historical portos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
