# Generated by Django 4.0.3 on 2023-05-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0017_porto_historicalshiftday_historicalporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalporto',
            name='flag',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='central.flag'),
        ),
        migrations.AddField(
            model_name='historicalporto',
            name='flag_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porto',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central.flag'),
        ),
        migrations.AddField(
            model_name='porto',
            name='flag_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalporto',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actief'),
        ),
        migrations.AlterField(
            model_name='porto',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actief'),
        ),
    ]
