# Generated by Django 4.0.3 on 2023-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0020_alter_historicalplanning_porto_alter_planning_porto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanning',
            name='porto_returned',
            field=models.IntegerField(default=False, verbose_name='Porto teruggebracht'),
        ),
        migrations.AddField(
            model_name='planning',
            name='porto_returned',
            field=models.IntegerField(default=False, verbose_name='Porto teruggebracht'),
        ),
    ]
