# Generated by Django 4.0.3 on 2023-05-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0021_historicalplanning_porto_returned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplanning',
            old_name='porto_returned',
            new_name='porto_lastreturned',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='porto_returned',
            new_name='porto_lastreturned',
        ),
    ]
