# Generated by Django 4.0.3 on 2023-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0022_rename_porto_returned_historicalplanning_porto_lastreturned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplanning',
            name='porto_lastreturned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Porto laatst teruggebracht'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='porto_lastreturned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Porto laatst teruggebracht'),
        ),
    ]
